"""Tailwind CSS config preset formatter."""

from tokens import classify_palette_tokens


def generate_tailwind_config(result: dict, palette_tokens: dict) -> str:
    """Generate a Tailwind CSS config preset from result and palette tokens.

    Expects result to contain: recommended_palette, foundation (optional),
    palette_display (optional, for comment).
    """
    foundation = result.get("foundation") or {}
    palette = result["recommended_palette"]
    display_name = result.get("palette_display") or palette

    classified = classify_palette_tokens(palette_tokens)
    colors = classified["colors"]
    font_display = classified["font_display"]

    # Merge foundation + palette overrides
    shadows = {**foundation.get("shadow", {}), **classified["shadows"]}
    radii = {**foundation.get("radius", {}), **classified["radii"]}
    spacing = foundation.get("spacing", {})
    durations = foundation.get("motion_duration", {})
    easings = foundation.get("motion_easing", {})
    font_sizes = foundation.get("font_size", {})
    font_weights = foundation.get("font_weight", {})
    opacity = foundation.get("opacity", {})
    z_index = foundation.get("z_index", {})

    # Build font families: foundation stacks + palette display override
    font_families = {}
    for name, stack in foundation.get("font_family", {}).items():
        font_families[name] = [s.strip() for s in stack.split(",")]
    if font_display:
        font_families["display"] = [font_display, "sans-serif"]

    lines = []
    lines.append("// Universal Design System — Tailwind Preset")
    lines.append(f"// Palette: {display_name}")
    lines.append("// Generated by: python src/scripts/design_system.py")
    lines.append("")
    lines.append("/** @type {{import('tailwindcss').Config}} */")
    lines.append("export default {")
    lines.append("  theme: {")
    lines.append("    extend: {")

    # Colors
    lines.append("      colors: {")
    for group, values in sorted(colors.items()):
        if isinstance(values, dict):
            lines.append(f"        '{group}': {{")
            for name, hex_val in sorted(values.items()):
                lines.append(f"          '{name}': '{hex_val}',")
            lines.append("        },")
        else:
            lines.append(f"        '{group}': '{values}',")
    lines.append("      },")

    # Spacing
    if spacing:
        lines.append("      spacing: {")
        for name, val in sorted(spacing.items(), key=lambda x: int(x[0]) if x[0].isdigit() else 0):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Shadows
    if shadows:
        lines.append("      boxShadow: {")
        for name, val in sorted(shadows.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Radii
    if radii:
        lines.append("      borderRadius: {")
        for name, val in sorted(radii.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Transition duration
    if durations:
        lines.append("      transitionDuration: {")
        for name, val in sorted(durations.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Transition timing function
    if easings:
        lines.append("      transitionTimingFunction: {")
        for name, val in sorted(easings.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Font families
    if font_families:
        lines.append("      fontFamily: {")
        for name, stack in sorted(font_families.items()):
            formatted = ", ".join(f"'{s}'" for s in stack)
            lines.append(f"        '{name}': [{formatted}],")
        lines.append("      },")

    # Font sizes
    if font_sizes:
        lines.append("      fontSize: {")
        for name, val in sorted(font_sizes.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Font weights
    if font_weights:
        lines.append("      fontWeight: {")
        for name, val in sorted(font_weights.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Opacity
    if opacity:
        lines.append("      opacity: {")
        for name, val in sorted(opacity.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    # Z-index
    if z_index:
        lines.append("      zIndex: {")
        for name, val in sorted(z_index.items()):
            lines.append(f"        '{name}': '{val}',")
        lines.append("      },")

    lines.append("    },")
    lines.append("  },")
    lines.append("};")

    return "\n".join(lines)
