/**
 * Generated by Universal Design System for: SaaS Landing Page
 * Palette: minimal-saas
 *
 * Usage: copy this file into your project root as tailwind.config.js
 * Regenerate: python src/scripts/design_system.py "saas landing page" --format tailwind
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,jsx,ts,tsx,vue,svelte}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#2563EB',
          secondary: '#3B82F6',
          accent: '#60A5FA',
          muted: '#DBEAFE',
        },
        bg: {
          primary: '#FFFFFF',
          secondary: '#F8F8FA',
          tertiary: '#F0F0F5',
        },
        text: {
          primary: '#111118',
          secondary: '#555566',
          tertiary: '#6B6B7B',
        },
        status: {
          success: '#059669',
          warning: '#D97706',
          error: '#DC2626',
          info: '#2563EB',
        },
        border: {
          DEFAULT: '#C8C8D4',
          input: '#8E8E9E',
          subtle: '#E8E8F0',
        },
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      fontFamily: {
        display: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      boxShadow: {
        xs: '0px 1px 2px 0px rgba(0,0,0,0.05)',
        sm: '0px 2px 4px 0px rgba(0,0,0,0.06), 0px 1px 2px 0px rgba(0,0,0,0.04)',
        md: '0px 4px 12px 0px rgba(0,0,0,0.08), 0px 2px 4px 0px rgba(0,0,0,0.04)',
        lg: '0px 12px 32px 0px rgba(0,0,0,0.12), 0px 4px 8px 0px rgba(0,0,0,0.06)',
        xl: '0px 24px 64px 0px rgba(0,0,0,0.16)',
      },
    },
  },
  plugins: [],
};
